### ISSUE TITLE
doesnt work for v7

### ISSUE THREAD

**Issue by shardyy** [19noam/Rewasd-Bypass#1]
its just doesnt work for 7.0 i think they patched it, probably works for lower versions

**Comment by 19noam** [comment]
Did you follow all the steps correctly?

**Comment by shardyy** [comment]
ofc

**Comment by 2twentyseven** [comment]
same not able to get it to wrok, perhaps due to version 7

**Comment by 19noam** [comment]
> same not able to get it to wrok, perhaps due to version 7

It works for me in version 7.0. Did you do the network address thing? Some people don't have it in their device manager.
