### ISSUE TITLE
Able to boot but won't work

### ISSUE THREAD

**Issue by VFYZ** [19noam/Rewasd-Bypass#5]
(full disclaimer, I'd say I'm pretty computer illiterate so go easy on me)
tbh I'm not sure if this is a me problem or not, but here goes: 
I've used rewasd before via a trial, and this wasn't a problem there.
I'm trying to emulate a switch controller on my MNK so I can play BOTW, and once I set up the configs and everything, hitting the apply button doesn't do anything. 
I'm not really sure what the problem is.
![delete](https://github.com/19noam/Rewasd-Bypass/assets/159475673/8fde5920-7235-49de-8d65-1d712b91d36d)

**Comment by 19noam** [comment]
You need to put your mouse and keyboard in a group🙂
