### ISSUE TITLE
Windows 11 System doesn't support

### ISSUE THREAD

**Issue by heisenyu** [19noam/Rewasd-Bypass#6]
I think it didnt worked for me because I tried to use step 3 and it says 

Platform checking......
d8 - Error: System doesn't support.
ECHO it's deactivated.
-----------------------------------
DONE! Press any button to continue
-----------------------------------

I have made all other steps (including the network address) please could you help me? i have used the last version 7.00.8447

**Comment by 19noam** [comment]
It's not a problem with windows 11, It's a problem with your hardware. I use windows 11 and it works perfectly fine.
